config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
  root "home#index"
  # Defines the root path route ("/")
  authenticated :admin_user do
    root to: "admin#index", as: :admin_root 
  end
  
  namespace :admin do
    resources :orders
    resources :categories
    resources :products do
      resources :stocks
    end
  end

  resources :categories, only: [:show]
  resources :products, only: [:show]
  get "admin" => "admin#index"
  get "cart" => "cart#show"
  post "checkout" => "checkouts#create"
  get "success" => "checkouts#success"
  get "cancel" => "checkouts#cancel"
  post "webhooks/mercadopago" => 'webhooks#mercadopago'
end

app/views/shared/_footer_user.html.erb
<footer class="bg-gray-800 text-white">
  <div class="max-w-6xl mx-auto px-4 py-10 md:py-20">
    <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
      <!-- About section -->
      <div class="space-y-8">
        <h3 class="text-sm font-semibold text-gray-200 tracking-wider uppercase">About Tienda</h3>
        <p class="text-white leading-6">
          Tienda is a leading online marketplace, offering a wide range of products to cater to all your needs. Our commitment to quality and customer service ensures a great shopping experience.
        </p>
      </div>

      <!-- Quick Links -->
      <div class="space-y-8">
        <h3 class="text-sm font-semibold text-gray-200 tracking-wider uppercase">Quick Links</h3>
        <ul class="mt-4 space-y-4">
          <li>
            <%= link_to "Home", root_path, class: "text-base leading-6 text-white hover:text-gray-100" %>
          </li>
          <!-- Añade más enlaces aquí -->
        </ul>
      </div>

      <!-- Contact information -->
      <div class="space-y-8">
        <h3 class="text-sm font-semibold tracking-wider uppercase text-gray-200">
          Contact
        </h3>
        <ul class="mt-4 space-y-4">
          <li>
            <p class="text-base leading-6 text-white">
              123 Ecom Lane <br>
              E-commerce City, EC 12345
            </p>
          </li>
          <li>
            <p class="text-base leading-6 text-white">
              Email: support@ecom.com
            </p>
          </li>
          <li>
            <p class="text-base leading-6 text-white">
              Phone: (123) 456-7890
            </p>
          </li>
        </ul>
      </div>
    </div>
    <div class="border-t border-gray-700 mt-8">
      <div class="max-w-6xl mx-auto px-4 py-6 md:flex md:items-center md:justify-between">
        <p class="mt-6 text-base leading-6 text-gray-400 md:mt-0 md:order-1">
          &copy; <%= Time.now.year %> Ecomm, Inc. All rights reserved.
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header_admin.html.erb
<aside class="hidden md:flex flex-col w-64 h-screen px-4 py-8 sticky top-0 bg-white border-r rtl:border-r-0 rtl:border-l dark:bg-gray-900 dark:border-gray-700">
    <a href="#" class="flex justify-center items-center">
        <%= image_tag 'logo.png', class: "w-auto h-16 sm:h-20" %>
    </a>
    <div class="flex justify-center items-center text-gray-600">
        <h2 class="mx-4 mt-2 font-medium">Dinocom Admin</h2>
    </div>

    <div class="flex flex-col justify-between flex-1 mt-6">
        <nav>
            <%= link_to admin_path, class: "flex items-center px-4 py-2 #{current_page?(admin_path) ? 'bg-blue-600 text-white pointer-events-none' : 'text-gray-600 hover:bg-gray-100 dark:hover:bg-gray-800 dark:hover:text-gray-200 hover:text-gray-700'} transition-colors duration-300 transform rounded-md dark:text-gray-400" do%>
                <%= icon('fa-solid', 'gauge-high', class:'w-5 h-5')%> 
                <span class="mx-4 font-medium"><%= t('header_admin.dashboard')%></span>
            <%end%>

            <%= link_to admin_products_path, class: "flex items-center px-4 py-2 mt-5 #{current_page?(admin_products_path) ? 'bg-blue-600 text-white pointer-events-none' : 'text-gray-600 hover:bg-gray-100 dark:hover:bg-gray-800 dark:hover:text-gray-200 hover:text-gray-700'} transition-colors duration-300 transform rounded-md dark:text-gray-400" do %>
                <%= icon('fa-solid', 'cart-shopping', class: 'w-5 h-5') %> 
                <span class="mx-4 font-medium">Products</span>
            <% end %>

            <%= link_to admin_categories_path, class: "flex items-center px-4 py-2 mt-5 #{current_page?(admin_categories_path) ? 'bg-blue-600 text-white pointer-events-none' : 'text-gray-600 hover:bg-gray-100 dark:hover:bg-gray-800 dark:hover:text-gray-200 hover:text-gray-700'} transition-colors duration-300 transform rounded-md dark:text-gray-400" do%>
                <%= icon('fa-solid', 'list', class:'w-5 h-5')%> 
                <span class="mx-4 font-medium"><%= t('header_admin.categories')%></span>
            <%end%>

            <%= link_to admin_orders_path, class: "flex items-center px-4 py-2 mt-5 #{current_page?(admin_orders_path) ? 'bg-blue-600 text-white pointer-events-none' : 'text-gray-600 hover:bg-gray-100 dark:hover:bg-gray-800 dark:hover:text-gray-200 hover:text-gray-700'} transition-colors duration-300 transform rounded-md dark:text-gray-400" do%>
                <%= icon('fa-solid', 'truck-fast', class:'w-5 h-5')%> 
                <span class="mx-4 font-medium">Orders</span>
            <%end%>

            <hr class="my-6 border-gray-200 dark:border-gray-600" />

            <%= link_to destroy_admin_session_path, data: {"turbo-method": :delete, "turbo-confirm": "Are you sure you want to sign out"}, class: "flex items-center px-4 py-2 mt-5 text-gray-600 transition-colors duration-300 transform rounded-md dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800 dark:hover:text-gray-200 hover:text-gray-700" do%>
                <%= icon('fa-solid', 'sign-out', class:'w-5 h-5')%> 
                <span class="mx-4 font-medium">Logout</span>
            <%end%>
        </nav>
    </div>
</aside>

<aside class="flex md:hidden flex-col items-center w-16 h-screen py-8 sticky top-0 bg-white border-r rtl:border-l rtl:border-r-0 dark:bg-gray-900 dark:border-gray-700">
    <nav class="flex flex-col flex-1 space-y-6">
        <a href="#" class="flex justify-center items-center">
            <%= image_tag 'logo.png', class: "w-auto h-6" %>
        </a>

        <%= link_to admin_path, class: "p-1.5 #{current_page?(admin_path) ? 'bg-blue-600 text-white pointer-events-none' : 'text-gray-600'} text-gray-700 focus:outline-nones transition-colors duration-200 rounded-lg dark:text-gray-200 dark:hover:bg-gray-800 hover:bg-gray-100" do%>
            <%= icon('fa-solid', 'gauge-high', class:'w-6 h-6')%>
        <%end%>

        <%= link_to admin_products_path, class: "p-1.5 #{current_page?(admin_products_path) ? 'bg-blue-600 text-white pointer-events-none' : 'text-gray-600'} text-gray-700 focus:outline-nones transition-colors duration-200 rounded-lg dark:text-gray-200 dark:hover:bg-gray-800 hover:bg-gray-100" do %>
            <%= icon('fa-solid', 'cart-shopping', class: 'w-6 h-6') %>
        <% end %>

        <%= link_to admin_categories_path, class: "p-1.5 #{current_page?(admin_categories_path) ? 'bg-blue-600 text-white pointer-events-none' : 'text-gray-600'} text-gray-700 focus:outline-nones transition-colors duration-200 rounded-lg dark:text-gray-200 dark:hover:bg-gray-800 hover:bg-gray-100" do%>
            <%= icon('fa-solid', 'list', class:'w-6 h-6')%>
        <%end%>

        <%= link_to admin_orders_path, class: "p-1.5 #{current_page?(admin_orders_path) ? 'bg-blue-600 text-white pointer-events-none' : 'text-gray-600'} text-gray-700 focus:outline-nones transition-colors duration-200 rounded-lg dark:text-gray-200 dark:hover:bg-gray-800 hover:bg-gray-100" do%>
            <%= icon('fa-solid', 'truck-fast', class:'w-6 h-6')%>
        <%end%>

        <hr class="my-6 border-gray-200 dark:border-gray-600" />

        <%= link_to destroy_admin_session_path, data: {"turbo-method": :delete, "turbo-confirm": "Are you sure you want to sign out"}, class: "p-1.5 text-gray-700 focus:outline-nones transition-colors duration-200 rounded-lg dark:text-gray-200 dark:hover:bg-gray-800 hover:bg-gray-100" do%>
            <%= icon('fa-solid', 'sign-out', class:'w-6 h-6')%>
        <%end%>
    </nav>
</aside>

app/views/shared/_header_user.html.erb
<header>

    <nav class="bg-gray-900 text-white w-screen fixed top-0">
        <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <div class="flex h-16 items-center justify-between">
                <div class="flex items-center">
                    <div class="flex-shrink-0">
                        <%= link_to root_path do %>
                            <%= image_tag 'logo.png', class: 'h-12 w-12 object-contain' %>
                        <% end %>
                    </div> 
                    <a class="text-2xl font-bold font-heading ml-3" href="#">
                        Dinocom
                    </a>       
                </div>
                <div class="ml-4 flex items-center md:ml-6 ">
                    <button type="button" class="relative rounded-full bg-gray-900 p-1 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800">
                        <%= render partial: 'shared/items' %>
                    </button>
                </div>
            </div>
        </div>
    </nav>

</header>

app/views/shared/_items.html.erb
<% if admin_signed_in? %>
    <%= link_to cart_path, class: 'text-white hover:underline py-2 rounded-md text-2xl font-medium' do %>
      <%= icon 'fa-solid', 'shopping-cart' %>
      <%# <span class="flex absolute -mt-9 ml-5">
        <span class="animate-ping absolute inline-flex h-3 w-3 rounded-full bg-pink-400 opacity-75"></span>
        <span class="relative inline-flex rounded-full h-3 w-3 bg-pink-500">
        </span>
      </span> %>
    <% end %>
  <%#= link_to 'Edit', '#', class: "mx-2 text-white hover:text-gray-200 font-bold text-xl" %>
  <%#= link_to 'Log out', '#', class: "mx-2 text-white hover:text-gray-200 font-bold text-xl", method: :delete, data: {
    turbo_method: :delete,
    turbo_confirm: 'Are you sure?'
  } %>
<% else %>
  <div class="flex items-center justify-between ">
    <%= link_to cart_path, class: 'text-white hover:underline py-2 rounded-md text-2xl font-medium' do %>
      <%= icon 'fa-solid', 'shopping-cart' %>
    <% end %>
    <%= link_to 'Log in', '#', class: "mx-2 text-white hover:text-gray-200 font-bold text-xl" %>
    <%= link_to 'Sign up', '#', class: "mx-2 bg-white text-blue-500 px-4 py-2 rounded-full hover:bg-blue-400 hover:text-white transition duration-300 font-bold" %>
  </div>
<% end %>